version: '3'

# Define the services used in the system
services:

  # nifi service
  nifi:
    # add capability to the service
    cap_add:
      # give the docker container direct access to network
      - NET_ADMIN
    # the image that the docker container will use
    image: apache/nifi
    # a nice name for the docker container so we can connect to it
    container_name: nifi
    # set environment variables for the service
    environment:
      # set web port open
      - NIFI_WEB_HTTP_PORT=8080
    # volumes enable access to files outside the container
    volumes:
      - /Users/kevin/data:/home/nifi
    # ports to map and open to the outside world
    ports:
      - "8080:8080/tcp"
    # if the service fails, automatically restart. only stop when asked
    restart: unless-stopped
    
# declare used volumes
volumes:
  data: